login: &login
  adapter: mysql
  host: localhost
  username: root
  password: root

development:
  database: stips_development
  <<: *login

test:
  database: stips_test
  <<: *login

production:
  database: p37r5007_stips
  adapter: mysql
  host: localhost
  username: p37r5007_root
  password: stips01
